version: 2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Install GPG Key
          command: |
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C0BA5CE6DC6315A3
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y ruby-full
            gem install fastlane
            fastlane --version
      - run:
          name: Build and Deploy
          command: |
            fastlane deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build