version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:3.3.4
      - image: circleci/android:api-30
    steps:
      - checkout
      - run:
          name: Install Fastlane
          command: |
            gem install fastlane
            fastlane --version
      - run:
          name: Build and Deploy
          command: |
            fastlane deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build